package com.dsports.pricing.domain.exception;

public enum PricingErrorCode {
    GENERIC,
    PRICE_NOT_FOUND,
    DUPLICATE_ACTIVE_PRICE,
    INVALID_PRICE,
    INVALID_CURRENCY,
    INVALID_EFFECTIVE_DATE,
    CANNOT_MODIFY_ARCHIVED,
    CANNOT_SCHEDULE_NON_DRAFT,
    CANNOT_ACTIVATE_ARCHIVED,
    OVERLAPPING_ACTIVE_PRICE,
    OPTIMISTIC_LOCKING_CONFLICT,
    VALIDATION_ERROR,
    INTERNAL_ERROR
}
