package com.dsports.payment.domain.payment.exception;

public enum PaymentErrorCode {
    PAYMENT_NOT_FOUND,
    PAYMENT_NOT_OWNED_BY_USER,
    DUPLICATE_PAYMENT,
    INVALID_STATUS_TRANSITION,
    PAYMENT_ALREADY_SUCCESSFUL,
    PAYMENT_ALREADY_CANCELLED,
    PAYMENT_ALREADY_REFUNDED,
    PAYMENT_ALREADY_FAILED,
    AMOUNT_MISMATCH,
    ORDER_NOT_FOUND,
    ORDER_NOT_OWNED_BY_USER,
    ORDER_ALREADY_PAID,
    CANNOT_REFUND_NON_SUCCESS_PAYMENT,
    CANNOT_CANCEL_TERMINAL_PAYMENT,
    GATEWAY_ERROR,
    OPTIMISTIC_LOCKING_CONFLICT,
    VALIDATION_ERROR,
    GENERIC,
    INTERNAL_ERROR
}
