package com.dsports.order.domain.checkout.exception;

public enum CheckoutErrorCode {
    MISSING_SHIPPING_ADDRESS,
    MISSING_DELIVERY_METHOD,
    CHECKOUT_EMPTY,
    CHECKOUT_EXPIRED,
    CHECKOUT_ALREADY_TERMINAL,
    CHECKOUT_NOT_FOUND,
    INVALID_STATUS_TRANSITION,
    ITEM_OUT_OF_STOCK,
    PRODUCT_NOT_FOUND,
    PRICE_NOT_FOUND,
    CART_EMPTY,
    CART_NOT_FOUND,
    CHECKOUT_NOT_OWNED_BY_CUSTOMER
}
