package com.dsports.cart.domain.exception;

public enum CartErrorCode {
    GENERIC,
    CART_NOT_FOUND,
    CART_NOT_ACTIVE,
    DUPLICATE_ACTIVE_CART,
    ITEM_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    PRODUCT_NOT_ACTIVE,
    INSUFFICIENT_STOCK,
    PRICE_NOT_FOUND,
    INVALID_QUANTITY,
    MAX_QUANTITY_EXCEEDED,
    MAX_ITEMS_EXCEEDED,
    INVALID_PRICE,
    INVALID_USER,
    INVALID_STATUS_TRANSITION,
    OPTIMISTIC_LOCKING_CONFLICT,
    VALIDATION_ERROR,
    INTERNAL_ERROR
}
