package com.dsports.identity.domain.exception;

public enum ErrorCode {

    GENERIC,
    INVALID_EMAIL,
    INVALID_PHONE_NUMBER,
    INVALID_CUSTOMER_NAME,
    INVALID_STATUS_TRANSITION,
    MISSING_ROLE,
    DUPLICATE_ROLE,
    DUPLICATE_EMAIL,
    OAUTH_PROVIDER_ALREADY_LINKED,
    MAX_AUTH_PROVIDERS_EXCEEDED,
    USER_NOT_FOUND,
    INVALID_PASSWORD,
    ACCOUNT_LOCKED,
    INVALID_DATE_OF_BIRTH,
    VALIDATION_ERROR,
    INTERNAL_ERROR;
}
