package com.dsports.identity.domain.exception;

public enum ErrorCode {

    GENERIC,
    INVALID_EMAIL,
    INVALID_PHONE_NUMBER,
    INVALID_CUSTOMER_NAME,
    INVALID_STATUS_TRANSITION,
    MISSING_ROLE,
    DUPLICATE_ROLE,
    DUPLICATE_EMAIL,
    OAUTH_PROVIDER_ALREADY_LINKED,
    MAX_AUTH_PROVIDERS_EXCEEDED,
    USER_NOT_FOUND,
    INVALID_PASSWORD,
    ACCOUNT_LOCKED,
    INVALID_DATE_OF_BIRTH,
    INVALID_ADDRESS,
    INVALID_POSTAL_CODE,
    INVALID_COUNTRY,
    INVALID_STATE,
    INVALID_PROFILE_IMAGE_URL,
    ADDRESS_NOT_FOUND,
    MAX_ADDRESSES_EXCEEDED,
    OPTIMISTIC_LOCKING_CONFLICT,
    VALIDATION_ERROR,
    INTERNAL_ERROR;
}
