package com.dsports.inventory.domain.exception;

public enum InventoryErrorCode {
    GENERIC,
    INVENTORY_NOT_FOUND,
    DUPLICATE_INVENTORY,
    INVALID_QUANTITY,
    INVALID_RESERVED_QUANTITY,
    INVALID_REORDER_LEVEL,
    INSUFFICIENT_STOCK,
    RESERVATION_EXCEEDS_AVAILABLE,
    STOCK_OUT_EXCEEDS_AVAILABLE,
    CANNOT_RESERVE_UNAVAILABLE_STOCK,
    CANNOT_STOCK_OUT_RESERVED_QUANTITY,
    OPTIMISTIC_LOCKING_CONFLICT,
    VALIDATION_ERROR,
    INTERNAL_ERROR
}
