package com.dsports.catalog.domain.exception;

public enum CatalogErrorCode {
    GENERIC,
    INVALID_SPORT_NAME,
    INVALID_CATEGORY_NAME,
    INVALID_BRAND_NAME,
    INVALID_SLUG,
    SPORT_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    BRAND_NOT_FOUND,
    INVALID_SKU,
    INVALID_PRODUCT_NAME,
    INVALID_IMAGE_URL,
    PRODUCT_NOT_FOUND,
    DUPLICATE_SKU,
    DUPLICATE_SPORT_NAME,
    DUPLICATE_CATEGORY_NAME,
    DUPLICATE_BRAND_NAME,
    DUPLICATE_SLUG,
    OPTIMISTIC_LOCKING_CONFLICT,
    ARCHIVED_ENTITY,
    VALIDATION_ERROR,
    INTERNAL_ERROR
}
