package com.dsports.order.domain.order.exception;

public enum OrderErrorCode {
    ORDER_NOT_FOUND,
    ORDER_NOT_OWNED_BY_USER,
    ORDER_EMPTY,
    INVALID_STATUS_TRANSITION,
    ORDER_ALREADY_CANCELLED,
    ORDER_ALREADY_DELIVERED,
    CHECKOUT_NOT_FOUND,
    CHECKOUT_NOT_VALIDATED,
    CART_NOT_FOUND,
    CART_EMPTY,
    INSUFFICIENT_STOCK,
    DUPLICATE_ORDER,
    OPTIMISTIC_LOCKING_CONFLICT,
    VALIDATION_ERROR,
    GENERIC,
    INTERNAL_ERROR
}
